### ISSUE TITLE
[069] Just one round of pomodoro timer?

### ISSUE THREAD

**Issue by pickfire** [pybites/100DaysOfCode#9]
Pomodoro timer looks cool but one round of it is kinda weird.

I have wrote an implementation at https://github.com/pickfire/spt, that is more like a pomodoro timer even though it does not open open a youtube video in web browser.

**Comment by pybites** [comment]
nice, thanks for sharing @pickfire - we will take a look

**Comment by bbelderbos** [comment]
We will do a pomodoro timer blog code challenge soon on our blog / platform. Stay tuned ...

**Comment by pybites** [comment]
Feel free to code + PR your work, we launched a pomodoro timer challenge this week: https://codechalleng.es/challenges/52
